name: 'Create GitHub Repo'
on: 
  workflow_call:
    inputs:
      repoName:
        description: 'Defines the repo name'
        required: true
        type: string
      templateRepoUrl:
        description: 'Defines the repo to use as a template to copy the code into'
        required: true
        type: string

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
    - name: 'Create new repo'
      run: |
        # Used for organization GitHub Accounts
        # repoOutput=$(curl -X POST 'https://api.github.com/orgs/${{ vars.GH_USER }}/repos' \
        # Used for Personal GitHub Accounts
        repoOutput=$(curl -X POST 'https://api.github.com/user/repos' \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -d '{"name":"${{ inputs.repoName }}","private":true}')
        newRepoApiUrl=$(echo $repoOutput | jq '.url' -r )
        if [ -z "$newRepoApiUrl" ]; then exit 2 ; fi 
        echo "newRepoApiUrl==$newRepoApiUrl" >> $GITHUB_ENV
    - name: 'Import template repo'
      run: |
        importOutput=$(curl -X PUT '${{ env.newRepoApiUrl }}/import' \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -d '{"vcs":"subversion","vcs_url":"${{ inputs.templateRepoUrl }}","vcs_username":"${{ vars.GH_USER }}","vcs_password":"${{ secrets.GH_TOKEN  }}"}')
        importStatus=$(echo $importOutput | jq '.status' -r )
        if [ -z "$importStatus" ]; then exit 2 ; fi 
