name: 'Create GitHub Repo'
on: 
  workflow_call:
    inputs:
      REPO_NAME:
        description: 'Defines the repo name'
        required: true
        type: string
      TEMPLATE_REPO_URL:
        description: 'Defines the repo to use as a template to copy the code into'
        required: true
        type: string
    outputs:
      NEW_REPO_URL:
        description: 'The URL of the new repo that was created'
        value: ${{ jobs.create_repo.outputs.NEW_REPO_API_URL }}
      NEW_REPO_FULL_NAME:
        description: 'The full name of the new repo that was created'
        value: ${{ jobs.create_repo.outputs.NEW_REPO_FULL_NAME }}

jobs:
  create_repo:
    runs-on: ubuntu-latest
    outputs:
      NEW_REPO_API_URL: ${{ env.NEW_REPO_API_URL }}
      NEW_REPO_URL: ${{ env.NEW_REPO_URL }}
      NEW_REPO_FULL_NAME: ${{ env.NEW_REPO_FULL_NAME }}
    steps:
    - name: 'Create new repo'
      run: |
        # Used for organization GitHub Accounts
        # repoOutput=$(curl -X POST 'https://api.github.com/orgs/${{ vars.GH_USER }}/repos' \
        # Used for Personal GitHub Accounts
        repoOutput=$(curl -X POST 'https://api.github.com/user/repos' \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -d '{"name":"${{ inputs.REPO_NAME }}","private":true}')
        newRepoApiUrl=$(echo $repoOutput | jq '.url' -r )
        newRepoName=$(echo $repoOutput | jq '.full_name' -r )
        newRepoUrl=$(echo $repoOutput | jq '.html_url' -r )
        if [ -z "$newRepoApiUrl" ]; then exit 2 ; fi 
        echo "New Repo API URL is: "$newRepoApiUrl
        echo "New Repo Name is: "$newRepoName
        echo "New Repo URL is: "$newRepoUrl
        echo "NEW_REPO_API_URL=$newRepoApiUrl" >> $GITHUB_ENV
        echo "NEW_REPO_URL=$newRepoApiUrl" >> $GITHUB_ENV
        echo "NEW_REPO_FULL_NAME=$newRepoUrl" >> $GITHUB_ENV
    - name: 'Import template repo'
      run: |
        importOutput=$(curl -X PUT '${{ env.NEW_REPO_API_URL }}/import' \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -d '{"vcs":"git","vcs_url":"${{ inputs.TEMPLATE_REPO_URL }}","vcs_username":"${{ vars.GH_USER }}","vcs_password":"${{ secrets.GH_TOKEN  }}"}')
        importStatus=$(echo $importOutput | jq '.status' -r )
        if [ -z "$importStatus" ]; then exit 2 ; fi 
