name: 'Initiate TFC Worksapce'
on: 
  workflow_call:
    inputs:
      WORKSPACE_NAME:
        description: 'Defines the workspace Name'
        required: true
        type: string
      ORG_NAME:
        description: 'Defines the Terraform Cloud organization name'
        required: true
        type: string
      TFC_REPO:
        description: 'Defines the URL that contains the workspace code'
        required: true
        type: string
      TFC_REPO_BRANCH:
        description: 'Defines the branch that contains the workspace code'
        required: true
        type: string

jobs:
  create_workspace:
    runs-on: ubuntu-latest
    steps:
    - name: 'Define runtime variables'
      run: |
        echo 'Im defining any runtime variables needed to be gathered from the inputs'
        mkdir ${{ github.workspace }}/temp
        echo "REPO_TEMP_PATH=${{ github.workspace }}/temp" >> $GITHUB_ENV
    - name: 'Checkout ${{ inputs.TFC_REPO }} that contains the Terraform workspace code'
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.TFC_REPO }}
        path: ${{ env.REPO_TEMP_PATH }}
        ref: ${{ inputs.TFC_REPO_BRANCH }}
    - name: 'Cheating and sleeping for 20 seconds to let import finish'
      run: |
        sleep 20
    - name: 'Update provider.tf to use the correct Org and Workspace name'
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: '___'
        tokenSuffix: '___'
        files: '${{ env.REPO_TEMP_PATH }}/provider.tf'
      env:
        ORG_NAME: ${{ inputs.ORG_NAME }}
        WORKSPACE_NAME: ${{ inputs.WORKSPACE_NAME }}
    # - uses: actions/checkout@v3
    - name: 'Commit and push changes to provider.tf to the repo: ${{ inputs.TFC_REPO }}'
      run: |
          cd ${{ env.REPO_TEMP_PATH }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated Org and Workspace name for Terraform Cloud"
          git push
    - name: 'Authenticate to Terraform Cloud and create workspace'
      run: |
        export TF_TOKEN_app_terraform_io=${{ secrets.TFC_TOKEN }}
        terraform init

# Next steps:
# 1. Figure how to run TF Init within Runner to create workspace
# 2. Define variables for within the TFC workspace
# 3. Run the Infra workspace to deploy the infra
        
