name: 'Initiate TFC Worksapce'
on: 
  workflow_call:
    inputs:
      workspaceName:
        description: 'Defines the workspace Name'
        required: true
        type: string
      apiToken:
        description: 'Defines the API token to authenticate with Terraform Cloud'
        required: true
        type: string
      orgName:
        description: 'Defines the Terraform Cloud organization name'
        required: true
        type: string

jobs:
  create_workspace:
    runs-on: ubuntu-latest
    steps:
    - name: 'Authenticate to Terraform Cloud'
      run: |
        export TF_TOKEN_app_terraform_io=${{ inputs.apiToken }}
        

# Next steps:
# 1. Figure how to run TF Init within Runner to create workspace
# 2. Define variables for within the TFC workspace
# 3. Run the Infra workspace to deploy the infra
        
