name: 'Trigger Workflow'
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Region'
        required: true
        default: 'CentralUS'
      templateRepoUrl: 
        description: 'URL of template repo'
        required: true
        default: ''
      lzName:
        description: 'Landing Zone Name'
        required: true
        default: ''
      tags:
        description: 'JSON to define tags'
        required: false
        default: '{}'


jobs:
  validate-inputs:
    runs-on: ubuntu-latest
    steps:
    - name: 'Output inputs received'
      run: |
        echo "The value stream is ${{ inputs.lzName }}"
        echo "The region is ${{ inputs.region }}."
        echo "Here is a list of the tags defined:"
        echo "${{ inputs.tags }}"
    - name: 'Define runtime variables'
      run: |
        echo 'Im defining any runtime variables needed to be gathered from the inputs'
    - name: 'Test if ${{ inputs.lzName }} exists'
      run: |
        repoTestOutput=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ env.GH_ORG }}/${{ inputs.lzName }})
        repoExists=$( echo $repoTestOutput | jq '.id' -r )
        if [ "$repoExists" != 'null' ]; then 
          repo_exists="true"
        else
          repo_exists="false"
        fi 
        echo $repo_exists
  call-workflow-create-gh-repo:
    uses: ./.github/workflows/create-gh-repo.yml
    with:
      repoName: ${{ inputs.lzName }}
      templateRepoUrl:  ${{ inputs.templateRepoUrl }}
    secrets: inherit

